version: "3.8"
services:
  wireguard_with_gui:
    image: wg-easy-with-metrics
    container_name: wireguard_with_gui
    ports:
      - "51820:51820/udp"
      - "51821:51821"
      - "9001:9001"
    restart: unless-stopped
    environment:
      - WG_HOST=192.168.2.33
      - PASSWORD='p123123'
      - WG_PORT=51820
      - WG_PERSISTENT_KEEPALIVE=30
      - WG_DEFAULT_DNS=1.1.1.1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/etc/wireguard
