version: "3.8"
services:
  wireguard_with_gui:
    image: wg-easy-with-metrics
    container_name: wireguard_with_gui
    ports:
      - "51820:51820/udp"
      - "51821:51821"
    restart: unless-stopped
    hostname: wireguard
    environment:
      - WG_HOST=${WGEASY_SERVER_HOST:-127.0.0.1}
      - PASSWORD=${WGEASY_ADMIN_PASSWORD:-p123123}
      - WG_PORT=${WGEASY_PORT:-51820}
      - WG_PERSISTENT_KEEPALIVE=30
      - WG_DEFAULT_DNS=${WGEASY_DNS:-1.1.1.1}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./wireguard:/etc/wireguard

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    #No need to open port of prometheus. It used internally by Grafana without auth.
    #ports:
    #  - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"

  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      - TZ="Europe/Moscow"
      - GF_SECURITY_ADMIN_USER=${WGEASY_GRAFANA_ADMIN_USERNAME:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${WGEASY_GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
