{
 "title": "WireGuard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "clients",
    "label": "Clients",
    "query": {
     "query": "label_values(wireguard_last_handshake_unixtimestamp, client_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "User activity status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "repeat": "clients",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - wireguard_last_handshake_unixtimestamp{client_name=\"$clients\"} < 150",
     "legendFormat": "{{client_name}}"
    },
    {
     "expr": "wireguard_last_handshake_unixtimestamp{client_name=\"$clients\"} * 1000 < time()*1000 - 150000",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total traffic by the ${__to:date:YYYY-MM} month",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(wireguard_send_bytes_gauge{client_name=~\"$clients\"}[${__to:date:D}d])) by (client_name) + sum(increase(wireguard_received_bytes_gauge{client_name=~\"$clients\"}[${__to:date:D}d])) by (client_name) > 0",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Download/Upload speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(wireguard_send_bytes_gauge{client_name=~\"$clients\"}[$__rate_interval])) by (client_name) > 0",
     "legendFormat": "{{client_name}} DOWN"
    },
    {
     "expr": "sum(rate(wireguard_received_bytes_gauge{client_name=~\"$clients\"}[$__rate_interval])) by (client_name) > 0",
     "legendFormat": "{{client_name}} UP"
    }
   ]
  },
  {
   "title": "Total traffic by time range",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(wireguard_send_bytes_gauge{client_name=~\"$clients\"}[$__range])) by (client_name) + sum(increase(wireguard_received_bytes_gauge{client_name=~\"$clients\"}[$__range])) by (client_name) > 0",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Download/Upload total",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(wireguard_send_bytes_gauge{client_name=~\"$clients\"}[$__interval])) by (client_name) > 0",
     "legendFormat": "{{client_name}} DOWN"
    },
    {
     "expr": "sum(increase(wireguard_received_bytes_gauge{client_name=~\"$clients\"}[$__interval])) by (client_name) > 0",
     "legendFormat": "{{client_name}} UP"
    }
   ]
  },
  {
   "title": "Clients activity",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "wireguard_last_handshake_unixtimestamp{client_name=~\"$clients\"} * 1000",
     "legendFormat": "{{client_name}}"
    }
   ]
  }
 ]
}